name: Example CI/CD Pipeline
  
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-ci-cd:
    name: Test Code, Build Docker, and Push to Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run backend tests
        working-directory: ./backend
        run: |
          chmod +x mvnw
          ./mvnw test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/my-project
          GIT_SHA=${{ github.sha }}

          docker build -t $IMAGE_NAME:backend-$GIT_SHA -t $IMAGE_NAME:backend-latest .

          docker push $IMAGE_NAME:backend-$GIT_SHA
          docker push $IMAGE_NAME:backend-latest
      
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        
      - name: Deploy to Kubernetes
        uses: appleboy/kubernetes-action@v0.0.1
        with:
          server: ${{ secrets.K8S_SERVER }}
          ca_cert: ${{ secrets.K8S_CA_CERT }}
          token: ${{ env.K8S_TOKEN }}
          templates: k8s/backend-*.yaml